console.log("rodando sistema de gerenciamento de jogos")
console.log("rodando sistema de gerenciamento de jogos e Apostas")
console.log("Enviando apostas")
console.log("Enviando jogos")
console.log("Enviando jogos sem premio")
console.log("Enviando jogos com premio")
console.log("Enviando teste commit")
console.log("Enviando teste git add")
console.log("Teste editando na console Web")
